In [1]:
import pandas as pd
pd.DataFrame({'A': [1, 2, 3]})

   A
0  1
1  2
2  3

In [4]:
# In [1]: 
import pandas as pd

# In [2]: 
pd.DataFrame({'A': [1, 2, 3]})

   A
0  1
1  2
2  3

In [5]:
In [3]: a = 1

In [4]: a
Out[4]: 1

In [6]:
a = 1
print(a)

1

# 10-Mintus in Pandas

In [7]:
In [1]: import numpy as np

In [2]: import pandas as pd

In [10]:
# Object Creation
s = pd.Series([1, 3, 5, np.nan, 6, 8])

s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [11]:
dates = pd.date_range("20130101", periods=6)
dates

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

In [12]:
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list("ABCD"))
df

                   A         B         C         D
2013-01-01  0.682099  1.079225  1.227497 -1.057289
2013-01-02 -0.775614 -0.627921  0.594636  0.677649
2013-01-03 -0.274074  1.347933  0.463698  1.364326
2013-01-04 -0.230252 -1.453455  0.666699 -2.107221
2013-01-05 -0.086965 -0.918236 -0.432559  0.200531
2013-01-06  1.208350 -0.262546 -2.277542  0.412761

In [13]:
df2 = pd.DataFrame(
    {
        "A": 1.0,
        "B": pd.Timestamp("20130102"),
        "C": pd.Series(1, index=list(range(4)), dtype="float32"),
        "D": np.array([3] * 4, dtype="int32"),
        "E": pd.Categorical(["test", "train", "test", "train"]),
        "F": "foo",
    }
)
df2

     A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

In [14]:
df2.dtypes

A          float64
B    datetime64[s]
C          float32
D            int32
E         category
F           object
dtype: object

In [17]:
df.head()

                   A         B         C         D
2013-01-01  0.682099  1.079225  1.227497 -1.057289
2013-01-02 -0.775614 -0.627921  0.594636  0.677649
2013-01-03 -0.274074  1.347933  0.463698  1.364326
2013-01-04 -0.230252 -1.453455  0.666699 -2.107221
2013-01-05 -0.086965 -0.918236 -0.432559  0.200531

In [18]:
df.index

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

In [19]:
df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

In [20]:
df.to_numpy()

array([[ 0.68209877,  1.07922464,  1.22749717, -1.05728878],
       [-0.77561378, -0.62792097,  0.59463577,  0.6776487 ],
       [-0.27407364,  1.34793272,  0.46369811,  1.36432594],
       [-0.2302523 , -1.45345463,  0.66669864, -2.10722079],
       [-0.08696457, -0.91823583, -0.43255907,  0.20053102],
       [ 1.20835035, -0.26254562, -2.2775423 ,  0.41276145]])

In [21]:
df2.dtypes

A          float64
B    datetime64[s]
C          float32
D            int32
E         category
F           object
dtype: object

In [22]:
df.describe()

              A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean   0.087257 -0.139167  0.040405 -0.084874
std    0.723458  1.121102  1.255735  1.268558
min   -0.775614 -1.453455 -2.277542 -2.107221
25%   -0.263118 -0.845657 -0.208495 -0.742834
50%   -0.158608 -0.445233  0.529167  0.306646
75%    0.489833  0.743782  0.648683  0.611427
max    1.208350  1.347933  1.227497  1.364326

In [23]:
df.T

   2013-01-01  2013-01-02  2013-01-03  2013-01-04  2013-01-05  2013-01-06
A    0.682099   -0.775614   -0.274074   -0.230252   -0.086965    1.208350
B    1.079225   -0.627921    1.347933   -1.453455   -0.918236   -0.262546
C    1.227497    0.594636    0.463698    0.666699   -0.432559   -2.277542
D   -1.057289    0.677649    1.364326   -2.107221    0.200531    0.412761

In [24]:
df

                   A         B         C         D
2013-01-01  0.682099  1.079225  1.227497 -1.057289
2013-01-02 -0.775614 -0.627921  0.594636  0.677649
2013-01-03 -0.274074  1.347933  0.463698  1.364326
2013-01-04 -0.230252 -1.453455  0.666699 -2.107221
2013-01-05 -0.086965 -0.918236 -0.432559  0.200531
2013-01-06  1.208350 -0.262546 -2.277542  0.412761

In [25]:
df.sort_index(axis=1, ascending=False)

                   D         C         B         A
2013-01-01 -1.057289  1.227497  1.079225  0.682099
2013-01-02  0.677649  0.594636 -0.627921 -0.775614
2013-01-03  1.364326  0.463698  1.347933 -0.274074
2013-01-04 -2.107221  0.666699 -1.453455 -0.230252
2013-01-05  0.200531 -0.432559 -0.918236 -0.086965
2013-01-06  0.412761 -2.277542 -0.262546  1.208350

In [26]:
df.sort_values(by="B")

                   A         B         C         D
2013-01-04 -0.230252 -1.453455  0.666699 -2.107221
2013-01-05 -0.086965 -0.918236 -0.432559  0.200531
2013-01-02 -0.775614 -0.627921  0.594636  0.677649
2013-01-06  1.208350 -0.262546 -2.277542  0.412761
2013-01-01  0.682099  1.079225  1.227497 -1.057289
2013-01-03 -0.274074  1.347933  0.463698  1.364326

In [27]:
df["A"]

2013-01-01    0.682099
2013-01-02   -0.775614
2013-01-03   -0.274074
2013-01-04   -0.230252
2013-01-05   -0.086965
2013-01-06    1.208350
Freq: D, Name: A, dtype: float64

In [28]:
df[0:3]

                   A         B         C         D
2013-01-01  0.682099  1.079225  1.227497 -1.057289
2013-01-02 -0.775614 -0.627921  0.594636  0.677649
2013-01-03 -0.274074  1.347933  0.463698  1.364326

In [29]:
df["20130102":"20130104"]

                   A         B         C         D
2013-01-02 -0.775614 -0.627921  0.594636  0.677649
2013-01-03 -0.274074  1.347933  0.463698  1.364326
2013-01-04 -0.230252 -1.453455  0.666699 -2.107221

In [30]:
df.loc[dates[0]]

A    0.682099
B    1.079225
C    1.227497
D   -1.057289
Name: 2013-01-01 00:00:00, dtype: float64

In [31]:
df.loc[:, ["A", "B"]]

                   A         B
2013-01-01  0.682099  1.079225
2013-01-02 -0.775614 -0.627921
2013-01-03 -0.274074  1.347933
2013-01-04 -0.230252 -1.453455
2013-01-05 -0.086965 -0.918236
2013-01-06  1.208350 -0.262546

In [32]:
df.loc["20130102":"20130104", ["A", "B"]]

                   A         B
2013-01-02 -0.775614 -0.627921
2013-01-03 -0.274074  1.347933
2013-01-04 -0.230252 -1.453455

In [33]:
df.loc[dates[0], "A"]

np.float64(0.6820987697307197)

In [34]:
df.at[dates[0], "A"]

np.float64(0.6820987697307197)

In [35]:
df.iloc[3]

A   -0.230252
B   -1.453455
C    0.666699
D   -2.107221
Name: 2013-01-04 00:00:00, dtype: float64

In [36]:
df.iloc[3:5, 0:2]

                   A         B
2013-01-04 -0.230252 -1.453455
2013-01-05 -0.086965 -0.918236

In [37]:
df.iloc[[1, 2, 4], [0, 2]]

                   A         C
2013-01-02 -0.775614  0.594636
2013-01-03 -0.274074  0.463698
2013-01-05 -0.086965 -0.432559

In [38]:
df.iloc[1:3, :]

                   A         B         C         D
2013-01-02 -0.775614 -0.627921  0.594636  0.677649
2013-01-03 -0.274074  1.347933  0.463698  1.364326

In [39]:
df.iloc[:, 1:3]

                   B         C
2013-01-01  1.079225  1.227497
2013-01-02 -0.627921  0.594636
2013-01-03  1.347933  0.463698
2013-01-04 -1.453455  0.666699
2013-01-05 -0.918236 -0.432559
2013-01-06 -0.262546 -2.277542

In [40]:
df.iloc[1, 1]

np.float64(-0.6279209650028591)

In [41]:
df.iat[1, 1]

np.float64(-0.6279209650028591)

#-Boolean indexing

In [42]:
df[df["A"] > 0]

                   A         B         C         D
2013-01-01  0.682099  1.079225  1.227497 -1.057289
2013-01-06  1.208350 -0.262546 -2.277542  0.412761

In [43]:
df[df > 0]

                   A         B         C         D
2013-01-01  0.682099  1.079225  1.227497       NaN
2013-01-02       NaN       NaN  0.594636  0.677649
2013-01-03       NaN  1.347933  0.463698  1.364326
2013-01-04       NaN       NaN  0.666699       NaN
2013-01-05       NaN       NaN       NaN  0.200531
2013-01-06  1.208350       NaN       NaN  0.412761

In [45]:
df2 = df.copy()
df2["E"] = ["one", "one", "two", "three", "four", "three"]
df2

                   A         B         C         D      E
2013-01-01  0.682099  1.079225  1.227497 -1.057289    one
2013-01-02 -0.775614 -0.627921  0.594636  0.677649    one
2013-01-03 -0.274074  1.347933  0.463698  1.364326    two
2013-01-04 -0.230252 -1.453455  0.666699 -2.107221  three
2013-01-05 -0.086965 -0.918236 -0.432559  0.200531   four
2013-01-06  1.208350 -0.262546 -2.277542  0.412761  three

In [47]:
s1 = pd.Series([1, 2, 3, 4, 5, 6], index=pd.date_range("20130102", periods=6))
s1

2013-01-02    1
2013-01-03    2
2013-01-04    3
2013-01-05    4
2013-01-06    5
2013-01-07    6
Freq: D, dtype: int64

In [48]:
df["F"] = s1

In [49]:
df.at[dates[0], "A"] = 0

In [50]:
df.iat[0, 1] = 0

In [52]:
df.loc[:, "D"] = np.array([5] * len(df))
df

                   A         B         C    D    F
2013-01-01  0.000000  0.000000  1.227497  5.0  NaN
2013-01-02 -0.775614 -0.627921  0.594636  5.0  1.0
2013-01-03 -0.274074  1.347933  0.463698  5.0  2.0
2013-01-04 -0.230252 -1.453455  0.666699  5.0  3.0
2013-01-05 -0.086965 -0.918236 -0.432559  5.0  4.0
2013-01-06  1.208350 -0.262546 -2.277542  5.0  5.0

In [55]:
df2 = df.copy()
df2[df2 > 0] = -df2
df2

                   A         B         C    D    F
2013-01-01  0.000000  0.000000 -1.227497 -5.0  NaN
2013-01-02 -0.775614 -0.627921 -0.594636 -5.0 -1.0
2013-01-03 -0.274074 -1.347933 -0.463698 -5.0 -2.0
2013-01-04 -0.230252 -1.453455 -0.666699 -5.0 -3.0
2013-01-05 -0.086965 -0.918236 -0.432559 -5.0 -4.0
2013-01-06 -1.208350 -0.262546 -2.277542 -5.0 -5.0

# Missing data

In [56]:
df1 = df.reindex(index=dates[0:4], columns=list(df.columns) + ["E"])
df1.loc[dates[0] : dates[1], "E"] = 1
df1

                   A         B         C    D    F    E
2013-01-01  0.000000  0.000000  1.227497  5.0  NaN  1.0
2013-01-02 -0.775614 -0.627921  0.594636  5.0  1.0  1.0
2013-01-03 -0.274074  1.347933  0.463698  5.0  2.0  NaN
2013-01-04 -0.230252 -1.453455  0.666699  5.0  3.0  NaN

In [57]:
df1.dropna(how="any")

                   A         B         C    D    F    E
2013-01-02 -0.775614 -0.627921  0.594636  5.0  1.0  1.0

In [58]:
df1.fillna(value=5)

                   A         B         C    D    F    E
2013-01-01  0.000000  0.000000  1.227497  5.0  5.0  1.0
2013-01-02 -0.775614 -0.627921  0.594636  5.0  1.0  1.0
2013-01-03 -0.274074  1.347933  0.463698  5.0  2.0  5.0
2013-01-04 -0.230252 -1.453455  0.666699  5.0  3.0  5.0

In [59]:
pd.isna(df1)

                A      B      C      D      F      E
2013-01-01  False  False  False  False   True  False
2013-01-02  False  False  False  False  False  False
2013-01-03  False  False  False  False  False   True
2013-01-04  False  False  False  False  False   True

## Before Operations